version: '3'
services:
  app_postgres:
    image: "mdillon/postgis"
    ports:
      - 63000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ads_webapp_baseline
  app_redis:
    image: redis:3.2
    ports:
      - 63001:6379
  app:
    build: .
    volumes:
      - ./api:/app/api
      - ./public:/app/public
      - ./src:/app/src
      - ./build:/app/build
    depends_on:
      - app_postgres
      - app_redis
    links:
      - app_postgres
      - app_redis
    ports:
      - 63002:3000 # React Development Server
      - 63003:3001 # Web API
      - 63004:5858 # Debugging port for Web API
    environment:
      DATABASE_URL: postgres://postgres:password@app_postgres:5432/ads_webapp_baseline
      REDIS_URL: redis://app_redis:6379
    command: ["./wait-for-it.sh", "pg:5432", "--", "npm", "run", "develop:docker"]
    restart: always
